name: 'Test Report'
on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
jobs:
  report:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11']

    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1.6.0
      with:
        artifact: test-results-${{ matrix.python-version }}
        name: Test report - ${{ matrix.python-version }}
        path: test-results.xml
        reporter: java-junit
